### ISSUE TITLE
Get rid of inline-styles? CSP

### ISSUE THREAD

**Issue by kabo** [no23reason/react-qr-svg#136]
Would it be possible to get rid of inline styles?
This currently doesn't work with Content-Security-Policy without `style-src 'unsafe-inline'`.

**Comment by no23reason** [comment]
Hi, it's always nice to see an issue with PR included, thank you :) If I understand you correctly, alongside your PR adding the CSS classes, you also want to remove [this line](https://github.com/no23reason/react-qr-svg/blob/master/src/components/qr-svg.js#L34), right? That would either be a breaking change (I'm not necessarily against that) or we should use some sort of toggle, something like `useCss` or something. What do you think?

**Comment by kabo** [comment]
Well, it actually works as it is now. There's a warning in the console about the inline style, but the style is ignored by the browser when the CSP doesn't allow `unsafe-inline`. So the issue subject is actually misleading.
But you're right, it would be nicer if there was a way to remove the style attribute.

I'm a bit short on time at the moment (hence the long time to reply), so it's unlikely I'll try to amend my PR in the next couple of weeks. If you or anyone would like to refine it that'd be cool, if not I'll look into it when I have more time.

**Comment by no23reason** [comment]
I see, I'll try to look into it when I can. Thanks for your time :)
