### ISSUE TITLE
How can I render QR Code on a PDF?

### ISSUE THREAD

**Issue by iCHAIT** [no23reason/react-qr-svg#268]
I need to render a QR code on a PDF which my end-user can download. FOr creating the pdf I am using [`react-pdf/renderer`](https://www.npmjs.com/package/@react-pdf/renderer).

Here is my code - 

```javascript
import React from "react";
import {Page, Text, View, Document, StyleSheet, Image} from "@react-pdf/renderer";
import { QRCode } from "react-qr-svg";


export function PdfDocument(props) {
    return (
        <Document>
        <Page size="A4">    
          <View>
            <Text>Section #1</Text>
          </View>
          <View>
            <Text>Section #2</Text>
            <QRCode
                bgColor="#FFFFFF"
                fgColor="#000000"
                level="Q"
                style={{ width: 256 }}
                value="some text"
            />
          </View>
        </Page>
      </Document>
    );
}
```

The above gives me the following error - 

`Error: Invalid element of type rect passed to PDF renderer`

What I am doing wrong? How can I render a QR code on the fly onto a PDF?

**Comment by no23reason** [comment]
Hi, from the error message it seems as if the PDF renderer you use does not support rendering of SVG (because `rect` is a valid SVG element type). You will probably have to use some other PDF renderer or ask for support for your current one.

**Comment by iCHAIT** [comment]
I see. Thanks for your response @no23reason
