### ISSUE TITLE
Add logo image?

### ISSUE THREAD

**Issue by MovingGifts** [no23reason/react-qr-svg#301]
Hi, is there any way to add a logo to the center of the svg qr code and be able to download it as part of the code where it is nice and crisp?

Unfortunately with `qrcode.react` I can't find a way to download the qr code with a logo image in the center when using svg, which is needed for print quality.

Any ideas?

**Comment by no23reason** [comment]
Hi, the `qrcode.react` does not include the image itself directly into the QR code (it uses a link), that is why  you cannot download it. However, it is a better library than this, so please try to open a feature request there if you can.

**Comment by MovingGifts** [comment]
Cool will do, thank you!
