### ISSUE TITLE
onLoad event not firing up

### ISSUE THREAD

**Issue by abdulghanitech** [no23reason/react-qr-svg#385]
I'm trying to listen for svg on load events but it's not happening.
Here's my code snippet.

```
 <QRCode
                        id="qrForRestaurant"
                        level="Q"
                        width={407}
                        onLoad={() => console.log("qr loaded")}
                        value={JSON.stringify(currentSelectedRestaurant)}
                    />
```

version: "react-qr-svg": "2.2.2",
please help!

**Comment by no23reason** [comment]
Hi, the only props we support are specified here: https://github.com/no23reason/react-qr-svg/blob/master/src/components/qr-svg.js#L63
The QR should be "loaded" as soon as it is rendered, because there are no async operations.
Why do you need the `onLoad` callback?

**Comment by abdulghanitech** [comment]
Because i need to perform certain operations after the qr image is loaded!

**Comment by no23reason** [comment]
Those actions can be triggered in `componentDidMount` of the component that renders the `react-qr-svg`.

**Comment by no23reason** [comment]
Closing as inactive
