### ISSUE TITLE
Function get qrcode as SVG

### ISSUE THREAD

**Issue by Neofield-Dylan** [no23reason/react-qr-svg#391]
Is there some function that I can get the Qrcode as svg ?

To clarify my use case:
I want to generate many qrcodes at once and put all together in a A4 page to print all together. So, then, I do not need to print each one, one by one.
I know that I could create a page rendering all Qrcode components, and, then, add a button to print all this page. But, I would like to have a nicer UX and just add a button 'print all qrcodes' on the bottom of my table page, and, then had a downloadable svg with all qrcodes generated at runtime. For this, I need a function that I pass the value to be encrypted and the logo (also some others params like ecLevel, size, almost all the inputs the components have) and get the qrcode svg. Is there such function in this lib ?

Thanks in advance for the help.

**Comment by no23reason** [comment]
Hi, unfortunately there is no such function in the library. However you could build it by rendering the QRCodes yourself in some hidden div?

**Comment by Neofield-Dylan** [comment]
Oh, Hi!

 Thanks for reply me.  But, I already got this. 

My solution was to use [this lib](https://www.npmjs.com/package/qrcode-svg) to generate the qrcodes as svg string, then I create a svg with these qrcodes svgs to put all together in a A4 page. All of this, I done in server side. Then, the backend send this complete svg to frontend when user hit the button to download it.

Thanks again for your reply. Bye.
