### ISSUE TITLE
qr.js -> qrious?

### ISSUE THREAD

**Issue by karland** [no23reason/react-qr-svg#80]
Hi,

as far I as I understand your dependency `qr.js` has been renamed into [`qrious`](https://github.com/neocotic/qrious). It is currently in version is 4.02 with some breaking changes to previous versions. Are you planning an update to `qrious`? Thanks a lot.

**Comment by no23reason** [comment]
Hi, thanks for the comment. However qrious does not expose the QR code generation logic and only supports rendering to bitmap targets (or I was not able to find it). Therefore the migration does not make much sense, do you agree?

**Comment by karland** [comment]
Thanks for your fast response. I am not sure, if I answer your question correctly:

1. the code for generating QR code is in a package [`qrious-core`](https://github.com/neocotic/qrious-core) which is a dependency of `qrious`. 

2. I have not looked at the underlying code from your `react-qr-svg` or from `qr.js` or from `qrious`, so I am not sure which API calls you are using in order to generate the SVG. However comparing the APIs of [qr.js API](https://www.npmjs.com/package/qr-js) and [qrious API](https://www.npmjs.com/package/qrious) they appear pretty similar.

3. To understand the svg generating process of your package I would need to make more research to see what you have done with `qr.js` and if this not available any longer in its successor `qrious`.

**Comment by no23reason** [comment]
Oh I see the source of the confusion now.
You are right the two APIs you mention are compatible.
However, you are referring to the package [`qr-js`](https://www.npmjs.com/package/qr-js) (notice the dash) which only calls itself qr.js in their docs.
This project uses the [`qr.js`](https://www.npmjs.com/package/qr.js) (dot) that has different API and purpose (it basically just returns a 2D array of `true` / `false` values representing the code).

**Comment by karland** [comment]
Sorry and thanks for the clarification...

**Comment by no23reason** [comment]
No problem 🙂
