### ISSUE TITLE
Warning about key with React 16.0.0

### ISSUE THREAD

**Issue by karland** [no23reason/react-qr-svg#88]
When upgrading to React 16.0.0 I get the following warning:

> Warning: Each child in an array or iterator should have a unique "key" prop. See https://fb.me/react-warning-keys for more information.
    in svg (created by QRCode)

**Comment by no23reason** [comment]
Hi, thank you for spotting this bug, the key is really missing. I'll try to fix it later today.

**Comment by karland** [comment]
Awesome, thank you. When are you including it and would you build a new version?

**Comment by no23reason** [comment]
Sorry for delaying this, I ran into problems with my infrastructure packages (that create the demo page), which don't support React 16 yet. I will release a minor version this evening (I'm at CEST) that adds the key and extends the `peerDependencies` version range. So tomorrow at this our, there should be a new version on npm :)

**Comment by no23reason** [comment]
The 2.1.0 version is now React 16 ready

**Comment by karland** [comment]
Thanks. I already installed it and it works perfectly. Warnings are all gone.
