### ISSUE TITLE
support Kanji

### ISSUE THREAD

**Issue by peonmodel** [no23reason/react-qr-svg#99]
Hi,
would you consider basing the generator library on this instead?
https://github.com/kazuhikoarase/qrcode-generator

it support Kanji and various other modes and is otherwise identical

**Comment by no23reason** [comment]
Hello, thank you for the suggestion. Unfortunately, I don't know Kanji. Can you please provide a test case? I tried my library and [the one you suggested](https://runkit.com/no23reason/5a3638ccbc86e400110f4936) with this string 教育漢字 copied from wikipedia and both libraries showed me the same (wrong) text when I read the generated text with my iPhone default camera app.

**Comment by peonmodel** [comment]
hmm..., this is working fine for me
```js
const typeNumber = 0;  // auto
const errorCorrectionLevel = 'L';
const qrValue = `敦煌天空的沙礫帶著我們的記憶`;
const qr = qrcode(typeNumber, errorCorrectionLevel);
qr.addData(qrValue, 'Kanji');  // Kanji, important
qr.make()
svg = qr.createSvgTag();
```
did you also import the file "qrcode_SJIS.js" for the Kanji support?

there are some minor characters not supported though

**Comment by no23reason** [comment]
I can't get it to work in a Node.js file. How dow you import the `qrcode_SJIS.js` file?
When I do
```js
const qrcode = require("qrcode-generator")
require("qrcode-generator/qrcode_SJIS")
const qr = qrcode(0, "L");
qr.addData(`敦煌天空的沙礫帶著我們的記憶`, `Kanji`);
qr.make();
console.log(qr.createSvgTag());
```
it dies on an reference error in the `qrcode_SJIS` saying that qrcode is not defined 😕

**Comment by peonmodel** [comment]
perhaps this will be easier
i did a bit of rewrite based on that code for chaining syntax and using the ES6 export syntax
i also changed the default encoding to UTF-8, which is also provided but not set as default
[qrcode.txt](https://github.com/no23reason/react-qr-svg/files/1565518/qrcode.txt)
```js
import { QRCode } from '../../lib/mycode.js';
const qrValue = `敦煌天空的沙礫
	帶著我們的記憶`;
const typeNumber = 0;  // auto
const errorCorrectionLevel = 'L';  //
const { svg } = new QRCode(typeNumber, errorCorrectionLevel).addData(qrValue).addData('mixed').make().createSVGTag({ x: 0, y: 0, margin: 0 });
```

**Comment by no23reason** [comment]
While this would probably work, I don't think we should copy code from the source project.
I opened [an issue](https://github.com/kazuhikoarase/qrcode-generator/issues/47) in the source repository on how to properly include the Kanji file.

**Comment by no23reason** [comment]
The owner of the package you referenced shown me how to make the Kanji (UTF-8 in fact) support work. I'll look into making this work in my library during the holidays.

**Comment by Senderek** [comment]
Hi, did you resolve this issue? It would also help for other native characters. I would love to have additional prop named stringToBytesMode: PropTypes.oneOf(['SJIS', 'UTF-8' ...]).

**Comment by no23reason** [comment]
Hi, sorry, I didn't. If you need this feature I think [qrcode.react](https://github.com/zpao/qrcode.react) might be a better alternative to this. They have added SVG support (that is superior) since this package was started and they do support Kanji and I believe other character sets.
